name: Test if env variable exists before running step

on: [ 'workflow_dispatch', 'push' ]

env:
  JIRA_INPUT: $$ {{ vars.JSON_INPUT }}

jobs:
  checking-env:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check env variable 1
        run: echo "this should not have run"
        if: ${{ env.JIRA_INPUT != '' }}
