name: Run Python Script and Echo JSON

on:
  push:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install Python dependencies
      run: pip install json os

    - name: Run Python script and set env var
      run: |
        echo "JSON_INPUT=$(python scripts/main.py)" >> $GITHUB_ENV

    - name: Echo JSON_INPUT
      run: echo "JSON_INPUT=$JSON_INPUT"
