name: Run Python Script and Echo JSON

on:
  push:
  workflow_dispactch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Python script
      run: python your_script.py

    - name: Echo JSON_INPUT
      run: echo "JSON_INPUT=$JSON_INPUT"
